### ISSUE TITLE
Multitest correction

### ISSUE THREAD

**Issue by Rachine** [minepy/mictools#4]
Hello, 

Thank you very much for all the work on the package minepy and all the tools in mictools

This isa conceptual issue for my own understanding I would say, not code use. 

Why do we need to use multitest correction, while we are already testing the TICe against all the resampled TICe pvals?

Is it an addition from the https://academic.oup.com/gigascience/article/7/4/giy032/4958979 to be very conservative? is it also advised in the original procedure from http://jmlr.csail.mit.edu/papers/v17/15-308.html ? 

Thank you very much for your help! 

Best

**Comment by davidealbanese** [comment]
Dear @Rachine,

> Why do we need to use multitest correction, while we are already testing the TICe against all the resampled TICe pvals?

We don't "test the TICe values against the resampled TICe pvals". We empirically estimate the TICe p-values computing the empirical TICe null distribution. The multiple testing correction is necessary to control the FWER or the FDR. See https://academic.oup.com/gigascience/article/7/4/giy032/4958979#115495086.

> Is it an addition from the https://academic.oup.com/gigascience/article/7/4/giy032/4958979 to be very conservative?

No. MICtools implements the procedure described in the paper.

>  is it also advised in the original procedure from http://jmlr.csail.mit.edu/papers/v17/15-308.html ?

As you can see, the strategy is mentioned at page 28.

Davide
