### ISSUE TITLE
AttributeError: module 'mictools' has no attribute 'mergenull'

### ISSUE THREAD

**Issue by wqssf102** [minepy/mictools#7]
Hello
When i run: mictools mergenull 00.txt 11.txt uu.txt ( note: 00.txt and 11.txt were generated by 'mictools null …', respectively) , i got the error message: AttributeError: module 'mictools' has no attribute 'mergenull'. Based on Win platform and Linux (py2.7 and 3.7). may I know what is the reason?
Looking forward to your reply，thanks.
                                                                                                           Yours
                                                                                                        Qiusheng WU

**Comment by davidealbanese** [comment]
Please update mictools to the latest version.
