### ISSUE TITLE
Minepy in conda

### ISSUE THREAD

**Issue by Jediworm** [minepy/mictools#9]
Hello, I am trying to use minepy/mictools in conda but can't seem to get it to run. The commands are below:

conda create --name mictools
conda activate mictools
conda install -c bioconda minepy

When then running any commands such as mictools or minepy on their own, it simply says command not found. Is there something I'm doing wrong?

Sorry if this is a silly question, I cannot find any documentation about using it in conda

Thanks

**Comment by davidealbanese** [comment]
Dear @Jediworm, the minepy package in bioconda does not contain mictools. I suggest to use the mictools docker image.
